baseURL = "/"
languageCode = "en-us"
title = "Robert's blog"
theme = "hugo-traveler"

[author]
   Handle = "rmrobinson"
   FirstName = "Robert"
   LastName = "Robinson"
   Location = "Kitchener, ON"
   AboutPage = "/about"
