baseURL = "https://travel.rmrobinson.ca/"
languageCode = "en-us"
title = "Robert's Travels"
theme = "hugo-traveler"

[params]
   [params.author]
      Handle = "rmrobinson"
      FirstName = "Robert"
      LastName = "Robinson"
      Location = "Kitchener, ON"
      AboutPage = "https://blog.rmrobinson.ca"

[taxonomies]
   tag = 'tags'