baseURL = "/"
languageCode = "en-us"
title = "Robert's Travels"
theme = "hugo-traveler"

[author]
   Handle = "rmrobinson"
   FirstName = "Robert"
   LastName = "Robinson"
   Location = "Kitchener, ON"
   AboutPage = "https://blog.rmrobinson.ca"
